# Generated by Django 2.2.6 on 2019-10-13 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('available', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKLS', 'Weeks')], max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('powered', models.BooleanField(default=False)),
                ('added_date', models.DateField(default=datetime.date.today, verbose_name='date added')),
                ('watchers', models.IntegerField(default=0)),
            ],
        ),
    ]
